export const LANGUAGES = [
  "Indonesia",
  "United States",
  "United Kingdom",
  "Japan",
  "South Korea",
  "Malaysia",
  "Singapore",
  "Thailand",
  "Vietnam",
  "Philippines",
  "China",
  "India",
  "Australia",
  "Germany",
  "France",
  "Spain",
  "Italy",
  "Netherlands",
  "Brazil",
  "Argentina",
  "Mexico",
  "Canada",
  "Russia",
  "Turkey",
  "Saudi Arabia",
  "United Arab Emirates",
  "South Africa"
];

export const VERSIONS = [
  "Original",
  "Remix",
  "Live",
  "Cover",
  "Radio Edit"
];

export const ARTIST_ROLES = [
  "MainArtist",
  "FeaturedArtist",
  "Remixer"
];

export const CONTRIBUTOR_TYPES = [
  "Performer",
  "Producer",
  "Engineer",
  "Mixer",
  "Mastering Engineer"
];

export const EXPLICIT_OPTIONS = [
  "No",
  "Yes",
  "Clean"
];

export const TRACK_GENRES = [
  "Pop",
  "Rock",
  "Hip Hop",
  "R&B",
  "Jazz",
  "Classical",
  "Electronic",
  "Dangdut",
  "Indie",
  "Metal",
  "Folk",
  "Reggae",
  "Blues",
  "Country",
  "Soul"
];

export const SUB_GENRES_MAP: Record<string, string[]> = {
  "Pop": ["Dance Pop", "Synthpop", "Indie Pop", "Electropop", "K-Pop", "J-Pop", "Teen Pop", "City Pop"],
  "Rock": ["Alternative Rock", "Hard Rock", "Indie Rock", "Punk Rock", "Progressive Rock", "Grunge"],
  "Hip Hop": ["Trap", "Boom Bap", "Cloud Rap", "Drill", "Lo-Fi Hip Hop", "Conscious Hip Hop"],
  "R&B": ["Contemporary R&B", "Neo Soul", "Quiet Storm", "Alternative R&B"],
  "Jazz": ["Smooth Jazz", "Bebop", "Fusion", "Vocal Jazz", "Contemporary Jazz"],
  "Classical": ["Baroque", "Romantic", "Contemporary", "Classical Crossover"],
  "Electronic": ["House", "Techno", "Trance", "EDM", "Drum & Bass", "Dubstep"],
  "Dangdut": ["Dangdut Koplo", "Dangdut Melayu", "Dangdut Pop", "Dangdut Kontemporer"],
  "Indie": ["Indie Pop", "Indie Rock", "Indie Folk", "Bedroom Pop"],
  "Metal": ["Metalcore", "Heavy Metal", "Death Metal", "Black Metal", "Nu Metal"],
  "Folk": ["Acoustic", "Indie Folk", "Contemporary Folk"],
  "Reggae": ["Dancehall", "Roots Reggae", "Dub"],
  "Blues": ["Electric Blues", "Delta Blues", "Contemporary Blues"],
  "Country": ["Country Pop", "Bluegrass", "Alternative Country"],
  "Soul": ["Neo Soul", "Contemporary Soul", "Funk Soul"]
};

export const COUNTRIES_WITH_DIAL_CODES: { name: string; dialCode: string }[] = [
  { name: "Indonesia", dialCode: "+62" },
  { name: "Afghanistan", dialCode: "+93" },
  { name: "Albania", dialCode: "+355" },
  { name: "Algeria", dialCode: "+213" },
  { name: "Andorra", dialCode: "+376" },
  { name: "Angola", dialCode: "+244" },
  { name: "Argentina", dialCode: "+54" },
  { name: "Armenia", dialCode: "+374" },
  { name: "Australia", dialCode: "+61" },
  { name: "Austria", dialCode: "+43" },
  { name: "Azerbaijan", dialCode: "+994" },
  { name: "Bahrain", dialCode: "+973" },
  { name: "Bangladesh", dialCode: "+880" },
  { name: "Belarus", dialCode: "+375" },
  { name: "Belgium", dialCode: "+32" },
  { name: "Belize", dialCode: "+501" },
  { name: "Benin", dialCode: "+229" },
  { name: "Bolivia", dialCode: "+591" },
  { name: "Bosnia and Herzegovina", dialCode: "+387" },
  { name: "Botswana", dialCode: "+267" },
  { name: "Brazil", dialCode: "+55" },
  { name: "Brunei", dialCode: "+673" },
  { name: "Bulgaria", dialCode: "+359" },
  { name: "Burkina Faso", dialCode: "+226" },
  { name: "Cambodia", dialCode: "+855" },
  { name: "Cameroon", dialCode: "+237" },
  { name: "Canada", dialCode: "+1" },
  { name: "Chile", dialCode: "+56" },
  { name: "China", dialCode: "+86" },
  { name: "Colombia", dialCode: "+57" },
  { name: "Costa Rica", dialCode: "+506" },
  { name: "Croatia", dialCode: "+385" },
  { name: "Cuba", dialCode: "+53" },
  { name: "Cyprus", dialCode: "+357" },
  { name: "Czech Republic", dialCode: "+420" },
  { name: "Denmark", dialCode: "+45" },
  { name: "Dominican Republic", dialCode: "+1" },
  { name: "Ecuador", dialCode: "+593" },
  { name: "Egypt", dialCode: "+20" },
  { name: "El Salvador", dialCode: "+503" },
  { name: "Estonia", dialCode: "+372" },
  { name: "Ethiopia", dialCode: "+251" },
  { name: "Finland", dialCode: "+358" },
  { name: "France", dialCode: "+33" },
  { name: "Georgia", dialCode: "+995" },
  { name: "Germany", dialCode: "+49" },
  { name: "Ghana", dialCode: "+233" },
  { name: "Greece", dialCode: "+30" },
  { name: "Guatemala", dialCode: "+502" },
  { name: "Hong Kong", dialCode: "+852" },
  { name: "Hungary", dialCode: "+36" },
  { name: "Iceland", dialCode: "+354" },
  { name: "India", dialCode: "+91" },
  { name: "Iran", dialCode: "+98" },
  { name: "Iraq", dialCode: "+964" },
  { name: "Ireland", dialCode: "+353" },
  { name: "Israel", dialCode: "+972" },
  { name: "Italy", dialCode: "+39" },
  { name: "Japan", dialCode: "+81" },
  { name: "Jordan", dialCode: "+962" },
  { name: "Kazakhstan", dialCode: "+7" },
  { name: "Kenya", dialCode: "+254" },
  { name: "Kuwait", dialCode: "+965" },
  { name: "Kyrgyzstan", dialCode: "+996" },
  { name: "Laos", dialCode: "+856" },
  { name: "Latvia", dialCode: "+371" },
  { name: "Lebanon", dialCode: "+961" },
  { name: "Libya", dialCode: "+218" },
  { name: "Lithuania", dialCode: "+370" },
  { name: "Luxembourg", dialCode: "+352" },
  { name: "Macau", dialCode: "+853" },
  { name: "Madagascar", dialCode: "+261" },
  { name: "Malaysia", dialCode: "+60" },
  { name: "Mali", dialCode: "+223" },
  { name: "Malta", dialCode: "+356" },
  { name: "Mexico", dialCode: "+52" },
  { name: "Moldova", dialCode: "+373" },
  { name: "Monaco", dialCode: "+377" },
  { name: "Mongolia", dialCode: "+976" },
  { name: "Montenegro", dialCode: "+382" },
  { name: "Morocco", dialCode: "+212" },
  { name: "Mozambique", dialCode: "+258" },
  { name: "Myanmar", dialCode: "+95" },
  { name: "Namibia", dialCode: "+264" },
  { name: "Nepal", dialCode: "+977" },
  { name: "Netherlands", dialCode: "+31" },
  { name: "New Zealand", dialCode: "+64" },
  { name: "Nigeria", dialCode: "+234" },
  { name: "North Korea", dialCode: "+850" },
  { name: "Norway", dialCode: "+47" },
  { name: "Oman", dialCode: "+968" },
  { name: "Pakistan", dialCode: "+92" },
  { name: "Panama", dialCode: "+507" },
  { name: "Paraguay", dialCode: "+595" },
  { name: "Peru", dialCode: "+51" },
  { name: "Philippines", dialCode: "+63" },
  { name: "Poland", dialCode: "+48" },
  { name: "Portugal", dialCode: "+351" },
  { name: "Qatar", dialCode: "+974" },
  { name: "Romania", dialCode: "+40" },
  { name: "Russia", dialCode: "+7" },
  { name: "Saudi Arabia", dialCode: "+966" },
  { name: "Senegal", dialCode: "+221" },
  { name: "Serbia", dialCode: "+381" },
  { name: "Singapore", dialCode: "+65" },
  { name: "Slovakia", dialCode: "+421" },
  { name: "Slovenia", dialCode: "+386" },
  { name: "South Africa", dialCode: "+27" },
  { name: "South Korea", dialCode: "+82" },
  { name: "Spain", dialCode: "+34" },
  { name: "Sri Lanka", dialCode: "+94" },
  { name: "Sudan", dialCode: "+249" },
  { name: "Sweden", dialCode: "+46" },
  { name: "Switzerland", dialCode: "+41" },
  { name: "Syria", dialCode: "+963" },
  { name: "Taiwan", dialCode: "+886" },
  { name: "Tajikistan", dialCode: "+992" },
  { name: "Tanzania", dialCode: "+255" },
  { name: "Thailand", dialCode: "+66" },
  { name: "Tunisia", dialCode: "+216" },
  { name: "Turkey", dialCode: "+90" },
  { name: "Uganda", dialCode: "+256" },
  { name: "Ukraine", dialCode: "+380" },
  { name: "United Arab Emirates", dialCode: "+971" },
  { name: "United Kingdom", dialCode: "+44" },
  { name: "United States", dialCode: "+1" },
  { name: "Uruguay", dialCode: "+598" },
  { name: "Uzbekistan", dialCode: "+998" },
  { name: "Venezuela", dialCode: "+58" },
  { name: "Vietnam", dialCode: "+84" },
  { name: "Yemen", dialCode: "+967" },
  { name: "Zambia", dialCode: "+260" },
  { name: "Zimbabwe", dialCode: "+263" }
];
